[supervisord]
nodaemon=true
user=dpdns-laravel-danieljm
logfile=/home/dpdns-laravel-danieljm/htdocs/laravel.danieljm.dpdns.org/backstage/storage/logs/supervisord.log
pidfile=/home/dpdns-laravel-danieljm/htdocs/laravel.danieljm.dpdns.org/backstage/storage/supervisord.pid

[program:worker]
command=php artisan queue:work --queue=distributions,default --tries=3
directory=/home/dpdns-laravel-danieljm/htdocs/laravel.danieljm.dpdns.org/backstage
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/dpdns-laravel-danieljm/htdocs/laravel.danieljm.dpdns.org/backstage/storage/logs/worker.log

[program:reverb]
command=php artisan reverb:start
directory=/home/dpdns-laravel-danieljm/htdocs/laravel.danieljm.dpdns.org/backstage
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/dpdns-laravel-danieljm/htdocs/laravel.danieljm.dpdns.org/backstage/storage/logs/reverb.log

[program:scheduler]
command=php artisan schedule:work
directory=/home/dpdns-laravel-danieljm/htdocs/laravel.danieljm.dpdns.org/backstage
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/home/dpdns-laravel-danieljm/htdocs/laravel.danieljm.dpdns.org/backstage/storage/logs/scheduler.log
