[program:backstage-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/dpdns-laravel-danieljm/htdocs/laravel.danieljm.dpdns.org/backstage/artisan queue:work --queue=distributions --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/home/dpdns-laravel-danieljm/htdocs/laravel.danieljm.dpdns.org/backstage/storage/logs/queue-worker.log
stopwaitsecs=3600
